project:
  type: website
  output-dir: docs

website:
  title: "Craig Orman"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd
      - my_projects.qmd
      - research.qmd
      - classes.qmd

format:
  html:
    theme: Mint
    css: styles.css
    toc: true
