---
title: "About me"
about: 
  template: jolla
  links:
    - icon: linkedin
      text: Linkedin
      href: https://www.linkedin.com/in/craig-orman0/
    - icon: github
      text: Github
      href: https://github.com/ArgentCode
---

My name is Craig Orman, and I am a Junior in the Data Science Program at Iowa State University! When I am not studying or playing with data, I like to read, go hiking, and spend time with my lovely wife Carissa. 

## Experience:

#### Undergraduate Research Assistant
August 2022 - Present, Center for Statistical and Forensic Evidence, Ames, IA

#### Machine Learning Engineer Intern
May 2022 - August 2022, Principal Financial Group, Des Moines, IA

#### Software Engineering Intern
May 2021 - August 2021, Principal Financial Group, Des Moines, IA

#### Web Developer Intern
January 2021 - May 2021, eFuneral Solutions, Ames, IA

#### Security Officer
June 2020 - Present, Defense Contracting Activities, Ames IA

#### Section Supervisor
August 2019 - May 2020, US Marine Corps, Jacksonville, NC

#### Team Leader
March 2017 - August 2019, US Marine Corps, Jacksonville, NC

#### Radio Operator
June 2015 - March 2017, US Marine Corps, Jacksonville, NC
